### ISSUE TITLE
faacEncConfigurationPtr结构体中jointmode无法被识别

### ISSUE THREAD

**Issue by kaleidoscoope** [xnvi/faac-memory-optimization#1]
你好，我在用TMS320DM642这款DSP在CCS6.0.0环境下使用您简化之后的faac算法，想请问一下在faaccfg.h的结构体中定义的union里面有一个jointmode字段，不过在frame.c的调用中报错#137 struct "faacEncConfiguration" has no field "jointmode"；我尝试给union使用一个别名item依然报错，当我注释这些调用之后报错消失，但是AACstereo调用会使用jointmode字段

请问您有遇到过这方面的问题可以给我一些思路嘛？

**Comment by xnvi** [comment]
这个代码我已经在Linux，ESP32等多个环境下验证过，不会有问题。看你的描述推测应该是你的编译器不支持union或者对union有某些限制，这种问题我也无能为力。

**Comment by kaleidoscoope** [comment]
已经在CCS环境下解决了，联合体应该指定一个字段然后调用，我那个报错可能是调用太粗心了；不过我还发现另外一个问题，CCS是纯C环境，源码里面有一些C++的写法，需要改成C

**Comment by xnvi** [comment]
这个源码是纯C的，使用C99标准能编译过，C89编译会有问题。你说的C++语法在哪里，能列举一下吗？

**Comment by kaleidoscoope** [comment]
我简单调用了几个函数编译了一下，stereo.c和quantize.c里面有一个round-to-nearest函数lrint（）无法编译通过，查了下是C++的写法，我改成_nround（）编译通过，也可能是和我编译器本身有关系，其他问题暂时未发现

**Comment by xnvi** [comment]
lrint()函数是C99标准中math.h里的函数，并不是C++的写法，你的编译器对C99的支持不完整吗？C99标准请查阅这里 https://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf

**Comment by kaleidoscoope** [comment]
math.h部分大致翻了一下，那应该是支持不完整，会有一小部分函数我的编译器头文件里完全没有，有用到的话可能需要改成头文件支持的替代写法

**Comment by kaleidoscoope** [comment]
冒昧打扰，想请问一下您在linux下用的什么开发环境，我的板卡资源受限，想要用您的代码先看一下配置，以及大佬有否研究过faacEncGetConfiguration（）和faacEncSetConfiguration（）这两个函数的必要性，我观察到它本质上也是在配置hEncoder这个handle，如果不用会怎样？
